apiVersion: apps/v1
kind: Deployment
metadata:
  name: democm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: democm
  template:
    metadata:
      labels:
        app: democm
    spec:
      containers:
        - name: constellation-manager
          image: dimuthucs/cm:<<build_number>>
          ports:
            - containerPort: 8080
         
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: democm
spec:
  selector:
    app: democm
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
