apiVersion: apps/v1
kind: Deployment
metadata:
  name: demohm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demohm
  template:
    metadata:
      labels:
        app: demohm
    spec:
      containers:
        - name: health-monitor
          image: dimuthucs/hm:<<build_number>>
          ports:
            - containerPort: 8081
         
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: demohm
spec:
  selector:
    app: demohm
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
