apiVersion: apps/v1
kind: Deployment
metadata:
  name: demohm
  namespace: devenv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demohm
  template:
    metadata:
      labels:
        app: demohm
    spec:
      containers:
        - name: health-monitor
          image: gratien20191317/devhm:<<build_number>>
          ports:
            - containerPort: 8081
         
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: dev
spec:
  selector:
    app: dev
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
