apiVersion: apps/v1
kind: Deployment
metadata:
  name: demooc
  namespace: devenv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demooc
  template:
    metadata:
      labels:
        app: demooc
    spec:
      containers:
        - name: orbit-controller
          image: gratien20191317/devoc:<<build_number>>
          ports:
            - containerPort: 8082
         
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: dev
spec:
  selector:
    app: dev
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
