apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: orbit-controller
          image: dimuthucs/oc:<<build_number>>
          ports:
            - containerPort: 8082
         
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
